# **PROYECTO SCHUTZ EN PYTHON PARA CREACIÓN DE DASHBOARD 2 - PARTE 1**

## 1.- IMPORTACIÓN DE LIBRERÍAS PARA EL PROYECTO

In [14]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
from io import StringIO
from itertools import zip_longest
import io
import requests
from io import BytesIO
import pandas as pd
import chardet
import re
from oauth2client.service_account import ServiceAccountCredentials
import gspread
from gspread_dataframe import set_with_dataframe
from urllib.request import FancyURLopener
from urllib.request import urlopen
import urllib.request
import xml.etree.ElementTree as ET
import numpy as np
import datetime
import ssl
import warnings
from datetime import datetime, timedelta

In [15]:
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

warnings.filterwarnings("ignore", category=FutureWarning, message="Inferring datetime64.*")

## 2.- LECTURA DE DATAFRAMES

### 2.1 LECTURA "EMPLEADOS"

In [16]:
url = 'http://asp.maximise.cl/query.ashx?alias=gsea&user=excel_bd&password=excel_bd&filename=Gestion%5C%5CListo%20de%20Empleados%20Clasificados.txt'

# Descargar el archivo XML desde la URL
with urllib.request.urlopen(url) as response:
    xml_data = response.read()

# Parsear el archivo XML
root = ET.fromstring(xml_data)

# Crear una lista de diccionarios con los datos
data = []
for child in root:
    row = {}
    for subchild in child:
        row[subchild.tag] = subchild.text
    data.append(row)

# Convertir la lista de diccionarios en un dataframe de Pandas
df_empleados = pd.DataFrame(data)

In [17]:
# Imprimir el dataframe
df_empleados.to_csv('archivos_respaldo_dash2/df_empleados.csv', index = False)
df_empleados.sample(5)

,IDEMPLEADO,RUT,Nombre,apellidopaterno,apellidomaterno,idtipoempleado
20,8282106,24769866-3,Francisco Javier,Aguilar,Garcia,GE
241,14428523,14428523-9,Ruth Carolyn,Leyton,Arevalo,IN
691,19343402,19343402-9,Gerald Cristopher,Martinez,Carrasco,GE
403,16797382,16797382-5,Guillermo Isaias,Cocio,Chapa,EX
65,10309353,10309353-8,Pablo Dionicio,Escobar,Epulef,GE

### 2.2 LECTURA "MAESTRO DE PRODUCTOS"

In [20]:
import urllib.request

url = 'https://asp.maximise.cl/query.ashx?alias=gsea&user=excel_bd&password=excel_bd&filename=Gestion\Maestro%20de%20Productos.txt'

# Disable SSL certificate verification (not recommended for production)
with urllib.request.urlopen(url, context=ssl._create_unverified_context()) as response:
    xml_data = response.read()

# Parsear el archivo XML
root = ET.fromstring(xml_data)

# Crear una lista de diccionarios con los datos
data = []
for child in root:
    row = {}
    for subchild in child:
        row[subchild.tag] = subchild.text
    data.append(row)

# Convertir la lista de diccionarios en un dataframe de Pandas
df_productos = pd.DataFrame(data)

df_productos.sample(10)

,Part_Number,Descripcion,Categoria,Familia,Costo_Promedio,Ultimo_x0020_Costo,Fecha_Ultima_Compra
1348,P07121576,Tarjeta interfaz operador EST 3 4X-12SR interf...,P07,12,NaN,NaN,NaN
2526,S10272833,Destrabador Largo Electromagnetico con placa p...,S10,27,13823,13184.5,2023-06-06T00:00:00-04:00
2891,T14372323,Abrazadera OMEGA Metalica Ø16mm,T14,37,40,40,2019-11-11T00:00:00-03:00
2145,P08202832,"Tee 2 1/2"" NPT",P08,20,1800,NaN,2017-03-27T00:00:00-03:00
604,H21580495,Taladro percusion 13 mm,H21,58,54613,54613.44,2022-05-09T00:00:00-03:00
1095,I16431551,Relay (rele) 220 Volt,I16,43,9613,9613,2020-08-31T00:00:00-03:00
2448,S10252412,Lector Proximidad Rosslare AY-K12 125 kHz,S10,25,27580,27580,2023-03-30T00:00:00-03:00
355,C05631417,Telefono SIP X3SP estandar 2 ctas POE pantalla...,C05,63,21669,21668.9202,2017-03-24T00:00:00-03:00
773,H21582721,Taladro Rotomartillo Bosch GBH-2-24D 820W,H21,58,110840,110840,2023-06-07T00:00:00-04:00
2713,S12332309,Kit BFT para articular barreras rectangulares ...,S12,33,232148,232148,2021-03-08T00:00:00-03:00

### 2.3 LECTURA "LIBRO MAYOR BASE"

In [18]:
archivo_csv = 'archivos_respaldo/df_libro_mayor5_base2.csv'  # Reemplaza 'ruta_del_archivo.csv' con la ubicación real de tu archivo CSV
# Leer el archivo CSV y crear un DataFrame
df_libro_mayor_base = pd.read_csv(archivo_csv)
print("DIMENSIONES DE df_libro_mayor_base:", df_libro_mayor_base.shape)
df_libro_mayor_base.sample(10)

DIMENSIONES DE df_libro_mayor_base: (340, 5)

,CODIGO_PROYECTO,TIPO_CUENTA,TOTAL_LB,NOMBRE_OBRA,NOMBRE_CLIENTE
276,P-1683,3. COSTO MANO DE OBRA,0,CD BP-A05,EBCO S.A.
190,P-1626,1. INGRESO,0,CLINICA BIO BIO,CONSTRUCTORA LYD S.A.
111,P-1705,1. INGRESO,0,LOS CLARINES,CONSTRUCTORA INARCO S.A.
301,P-1701,4. COSTO SUPERVISIÓN,0,EDIFICIO ZENTENO,CONSTRUCTORA GREVIA SPA.
38,P-1675,2. COSTO MATERIALES,0,PALENA II,CONSTRUCTORA MYA SPA.
152,P-1723,2. COSTO MATERIALES,0,VILLA PANAMERICANA LOTE C,CONSTRUCTORA MENA Y OVALLE S.A.
243,P-1666,1. INGRESO,0,CD AXIONLONG,EBCO S.A.
201,P-1639,4. COSTO SUPERVISIÓN,0,LYON 2546,MOLLER Y PEREZ - COTAPOS CONSTRUCCIONES INDUST...
95,P-1699,2. COSTO MATERIALES,0,VILLA PANAMERICANA LOTE B,EMPRESA CONSTRUCTORA DLP S.A.
183,P-1611,4. COSTO SUPERVISIÓN,0,EDIFICIO PLAZA EGAÑA,EBCO S.A.

### 2.4 LECTURA "LIBRO MAYOR"

In [27]:
archivo_csv = 'archivos_respaldo/df_libro_mayor2.csv'  # Reemplaza 'ruta_del_archivo.csv' con la ubicación real de tu archivo CSV
# Leer el archivo CSV y crear un DataFrame
df_libro_mayor2 = pd.read_csv(archivo_csv)
print("DIMENSIONES DE df_libro_mayor:", df_libro_mayor2.shape)
df_libro_mayor2.sample(10)

DIMENSIONES DE df_libro_mayor: (24899, 18)

,Unnamed: 0,Codigo_proyecto,Cta_Contable,Año,Mes,Fecha,Tipo_Comp,Num_Comp,Glosa,Primer_Analisis,Referencia,Debito,Credito,Num_Referencia,Debito_2,Credito_2,TOTAL,Tipo_cuenta
7808,7808.00,P-1707,4150002-000,2023,5,2023-05-31T00:00:00-04:00,AJC,1844,REMUNERACIONES DIRECTAS PROYECTO,P-1707,18606841,886261,0,NaN,886261,0,-886261,COSTO MANO DE OBRA
13680,5380.00,P-1694,4101010-000,2023,5,2023-05-11T00:00:00-03:00,CIN,550,Carga 75 ohm terminal F con bloqueo de D,P-1694,C06112034,28204,0,51078,28204,0,-28204,COSTO MATERIALES
5580,5580.00,P-1716,4101010-000,2023,5,2023-05-17T00:00:00-04:00,CIN,946,"Conduit galvanizado EMT 20 x3000mm (1/2""",P-1716,T14370122,102000,0,51236,102000,0,-102000,COSTO MATERIALES
15579,7279.00,P-1699,4150002-000,2023,3,2023-03-31T00:00:00-03:00,AJC,1694,REMUNERACIONES DIRECTAS PROYECTO,P-1699,21055081,197285,0,NaN,197285,0,-197285,COSTO MANO DE OBRA
14740,6440.00,P-1707,4101010-000,2023,6,2023-06-08T00:00:00-04:00,CIN,268,Kit DSC PRO128 (central/teclado/fuente poder/g...,P-1707,S11282615,188056,0,51657,188056,0,-188056,COSTO MATERIALES
21647,5047.00,P-1725,4101010-000,2023,5,2023-05-05T00:00:00-03:00,CIN,124,Cinta Aisladora 3M Temflex 1500,P-1725,I16430107,2396,0,50892,2396,0,-2396,COSTO MATERIALES
11900,3600.00,P-1723,4101010-000,2023,4,2023-04-04T00:00:00-03:00,CIN,62,Roseta FTTH Plana c/guia SC/APC,P-1723,C08712545,50323,0,50188,50323,0,-50323,COSTO MATERIALES
20326,3726.00,P-1688,4101010-000,2023,4,2023-04-05T00:00:00-03:00,CIN,144,Conector de poder 3.5mm macho (para cama,P-1688,S09240029,1024,0,50238,1024,0,-1024,COSTO MATERIALES
6142,6142.00,P-1712,4101010-000,2023,6,2023-06-05T00:00:00-04:00,CIN,87,Amarras plasticas 300mm,P-1712,I16431048,1700,0,51515,1700,0,-1700,COSTO MATERIALES
10573,2273.00,P-1696,4101010-000,2023,2,2023-02-16T00:00:00-03:00,CIN,433,Broca HSS metal 6mm,P-1696,I17442579,5305,0,49471,5305,0,-5305,COSTO MATERIALES

## 3.- TRATAMIENTO DE DATAFRAMES

### 3.1- TRATAMIENTO 1 - EMPLEADOS

In [23]:
# Función para categorizar la columna 'idtipoempleado'

def categorizar_pl(idtipoempleado):
    if idtipoempleado =="GC" or idtipoempleado == "SC" or idtipoempleado == "TC":
        return 'CCDD'
    elif idtipoempleado =="GP" or idtipoempleado == "SP" or idtipoempleado == "TP":
        return 'PIPING'
    else:
        return 'OTRA'

# Crear la nueva columna 'idtipoempleado' aplicando la función
df_empleados['PL'] = df_empleados['idtipoempleado'].apply(categorizar_pl)
df_empleados.sample(10)

,IDEMPLEADO,RUT,Nombre,apellidopaterno,apellidomaterno,idtipoempleado,PL
125,12502891,12502891-8,Juan Agustin,Troncoso,Lagos,GE,OTRA
156,13062659,13062659-9,German Hugo,Torres,Becerra,EX,OTRA
768,20497896,20497896-4,Bryan Alexander,Vasquez,Riveros,TT,OTRA
707,19561822,19561822-4,Martin Alejandro,Contreras,Cruz,PI,OTRA
796,21198760,21198760-K,Gerald Ariel,Escobar,Escobar,EX,OTRA
316,15887129,15887129-7,Yerko Alejandro,Gonzalez,Vergara,PI,OTRA
687,19283436,19283436-8,Juan Eduardo,Lagos,Muñoz,CD,OTRA
8,7312675,7312675-4,Demetrio Roque,Agloni,Del Amo,AF,OTRA
346,16241233,16241233-7,Carlos Andres,Covarrubias,Molina,GE,OTRA
675,19183409,19183409-7,Alejandro Antonio,Pino,Pereira,GE,OTRA

In [24]:
# Visualización del dataframe formato PIVOT:
df_empleados_piv = pd.pivot_table(df_empleados, values=['IDEMPLEADO'], index=['PL'], aggfunc= 'count', fill_value=0)
df_empleados_piv

        IDEMPLEADO
PL
OTRA           896
PIPING           3

### 3.1- TRATAMIENTO 2 - LIBRO MAYOR

In [30]:
df_libro_mayor2.sample(5)

,Unnamed: 0,Codigo_proyecto,Cta_Contable,Año,Mes,Fecha,Tipo_Comp,Num_Comp,Glosa,Primer_Analisis,Referencia,Debito,Credito,Num_Referencia,Debito_2,Credito_2,TOTAL,Tipo_cuenta
444,444.00,P-1713,3101030-000,2023,5,2023-05-02T00:00:00-03:00,CVT,4,EP DR 51-54-2,P-1713,96568180-9,0,3617655,13718,0,3617655,3617655,INGRESO
5420,5420.00,P-1704,4101010-000,2023,5,2023-05-12T00:00:00-03:00,CIN,596,"Tee Mecanica 4"" x 2"" ranurada A-536",P-1704,P08202341,215644,0,51126,215644,0,-215644,COSTO MATERIALES
21929,5329.00,P-1707,4101010-000,2023,5,2023-05-10T00:00:00-03:00,CIN,500,Lector Standalone antivandalico Prox y C,P-1707,S10253109,221984,0,51023,221984,0,-221984,COSTO MATERIALES
15118,6818.00,P-1690,4101010-000,2023,6,2023-06-19T00:00:00-04:00,CIN,742,Camara domo Hikvision DS-2CE16C0T-IRF(2.,P-1690,S09222547,35820,0,51885,35820,0,-35820,COSTO MATERIALES
3650,3650.00,P-1721,4101010-000,2023,4,2023-04-04T00:00:00-03:00,CIN,81,Bateria 12V 7amp,P-1721,T14390028,46096,0,50207,46096,0,-46096,COSTO MATERIALES

In [45]:
# Función para categorizar la columna 'PRACTICA'

def categorizar_pl(referencia):
    if referencia.startswith("C02") or referencia.startswith("C03") or referencia.startswith("C05") or referencia.startswith("C06") or referencia.startswith("C08"):
        return 'TELECOMUNICACIONES'
    elif referencia.startswith("C04") or referencia.startswith("C07") or referencia.startswith("C05") or referencia.startswith("I16") or referencia.startswith("O1950") or referencia.startswith("P07") or referencia.startswith("S09") or referencia.startswith("S10") or referencia.startswith("S10") or referencia.startswith("S11") or referencia.startswith("S12") or referencia.startswith("S13") or referencia.startswith("T14"):
        return 'CCDD'
    elif referencia.startswith("I15") or referencia.startswith("O1951") or referencia.startswith("C05") or referencia.startswith("C06") or referencia.startswith("P08"):
        return 'PIPING'
    else:
        return 'OTRA'

# Crear la nueva columna 'idtipoempleado' aplicando la función
df_libro_mayor2['PRACTICA'] = df_libro_mayor2['Referencia'].apply(categorizar_pl)
df_libro_mayor2.sample(10)

,Unnamed: 0,Codigo_proyecto,Cta_Contable,Año,Mes,Fecha,Tipo_Comp,Num_Comp,Glosa,Primer_Analisis,Referencia,Debito,Credito,Num_Referencia,Debito_2,Credito_2,TOTAL,Tipo_cuenta,PRACTICA
1803,1803.00,P-1684,4101010-000,2023,2,2023-02-01T00:00:00-03:00,CIN,20,"Magnetico Embutido 1/4"" Blanco",P-1684,S11290198,37500,0,49238,37500,0,-37500,COSTO MATERIALES,CCDD
17958,1358.00,P-1693,4101010-000,2023,1,2023-01-19T00:00:00-03:00,CIN,740,"Union copla 6"" ranurada flexible",P-1693,P08200320,0,12470,48998,0,12470,12470,COSTO MATERIALES,PIPING
15702,7402.00,P-1725,4150002-000,2023,3,2023-03-31T00:00:00-03:00,AJC,1694,REMUNERACIONES DIRECTAS PROYECTO,P-1725,27111489,176120,0,NaN,176120,0,-176120,COSTO MANO DE OBRA,OTRA
571,571.00,P-1712,3101030-000,2023,5,2023-05-31T00:00:00-04:00,AJC,1823,VENTAS DE PROYECTO - CD VIÑA OTLET PARK,P-1712,76525290-3,0,15000000,NaN,0,15000000,15000000,INGRESO,OTRA
14479,6179.00,P-1727,4101010-000,2023,6,2023-06-05T00:00:00-04:00,CIN,104,Sierra Copa 20mm,P-1727,I15410225,14906,0,51533,14906,0,-14906,COSTO MATERIALES,PIPING
7380,7380.00,P-1680,4150002-000,2023,3,2023-03-31T00:00:00-03:00,AJC,1694,REMUNERACIONES DIRECTAS PROYECTO,P-1680,21591838,501718,0,NaN,501718,0,-501718,COSTO MANO DE OBRA,OTRA
20564,3964.00,P-1709,4101010-000,2023,4,2023-04-12T00:00:00-03:00,AJC,1434,COSTOS DE PROYECTOS,P-1709,COMPRA ALMUERZO,6039,0,NaN,6039,0,-6039,COSTO MATERIALES,OTRA
13277,4977.00,P-1706,4101010-000,2023,5,2023-05-04T00:00:00-03:00,CIN,102,Palanca Incendio SIGA-278 direc accion D,P-1706,P07120834,357315,0,50873,357315,0,-357315,COSTO MATERIALES,CCDD
19631,3031.00,P-1713,4101010-000,2023,3,2023-03-14T00:00:00-03:00,CIN,428,"Tornillo volcanita 6 x 2""",P-1713,I17440306,3200,0,49853,3200,0,-3200,COSTO MATERIALES,OTRA
16516,8216.00,P-OFICINA,4150002-003,2023,4,2023-04-30T00:00:00-03:00,AJC,1681,REMUNERACIONES DIRECTAS PROYECTO POR DISTRIBUIR,P-Oficina,20577191,47270,0,NaN,47270,0,-47270,OTRA,OTRA

## AQUI VOY